name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_threshold: 2% 
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_playlist: <iframe allow="" frameborder="" height="" style="" sandbox="" src="https://embed.music.apple.com/jp/playlist/%E3%82%BC%E3%83%AD/pl.u-76oNko6tvAkMWML"></iframe>
          
          
          
          
          
          
          
          
          
